version: "3"
services:
  ghost:
    image: "ghost:latest"
    restart: "always"
    ports:
      - "${GHOST_HTTP_PORT}:2368"
    environment:
      - "url=https://${COMPOSE_PROJECT_NAME}.stacks.run"
    volumes:
      - "${APP_CODE_PATH_HOST}:/var/lib/ghost/content"
volumes: {}
