version: '3.0'
services:
#  mysql:  
#   image: mariadb:${MARIADB_VERSION}
#   volumes:
#     - '${DATA_PATH_HOST}:/var/lib/mysql'
#   environment:
#     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
#     MYSQL_DATABASE: ${DB_NAME}
#     MYSQL_USER: ${DB_USER}
#     MYSQL_PASSWORD: ${DB_PASSWORD}
 ghost:  
  build: ./ghost
  volumes:
    - '${APP_CODE_PATH_HOST}:/ghost'
  ports:
    - '${GHOST_HTTP_PORT}:2368'
  environment:
    # database_client: mysql
    # database_connection_host: mysql
    # database_connection_user: ${DB_USER}
    # database_connection_password: ${DB_PASSWORD}
    # database_connection_database: ${DB_NAME}
    UID: 1000
    GID: 1000
    ADDRESS: http://localhost:38065
  # command: ["node", "current/index.js"]
