#User defined
user:
  # php_version:
  #   label:
  #     PHP version
  #   hint:
  #     Select a PHP version from the list above
  #   type:
  #     select
  #   values:
  #     - 7.0
  #     - 7.1
  #     - 7.2
  #     - 7.3
  #     - 7.4
  #   target:
  #     PHP_VERSION

  # install_xdebug:
  #   label:
  #     Install XDEBUG?
  #   type:
  #     checkbox
  #   hint:
  #     Check to enable XDEBUG installation
  #   target:
  #     INSTALL_XDEBUG
  # mysql_version:
  #   label:
  #     DataBase version
  #   hint:
  #     Select DataBase version
  #   type:
  #     select
  #   values:
  #     - "mysql"
  #     - "mariadb"
  #   target:
  #     DATABASE_VERSION

  # customize_server_root_path:
  #   label:
  #     Server root
  #   type:
  #     input
  #   values:
  #     /var/www
  #   hint:
  #     Server document root
  #   target:
  #     DOCUMENT_ROOT

#System defaults
system:
  show_localpath_selector:
    true
  #For collecting and storing DB in .env
  #db/user/password
  db_credentials:
    true
  #Generate public ports for the docker image
  ports:
    http:
      GHOST_HTTP_PORT
    others:
